### ISSUE TITLE
BUGS PARA GRUPO 8

### ISSUE THREAD

**Issue by OscarMelquiadesDuranNarganes** [Proyectos1-FDI-UCM/c2324-Grupo09#74]
Hola, miembros del grupo 8, puesto que me parece que no tenéis permisos para crear issues, os abro este hilo para documentar bugs.

**Comment by LuckyBlocks28** [comment]
Nombre del error (frase breve descriptiva)
La transición de cámara se detiene si el jugador se queda justo en el medio de esta en plena transición
Descripción
Cuando la cámara transiciona de una pantalla a otra si el jugador se ha detenido en el punto que permite la transición la cámara no volverá a la otra sala si el jugador quiere volver a la sala anterior.
Pasos

⦁	Paso 1: Producir la transición entre salas
⦁	Paso 2: Quedarse quieto en el punto exacto que permite hacer la transición
⦁	Paso 3: Andar hacia la sala de donde viniste
⦁	Paso 4: ¡Error producido!
![Captura de pantalla 2024-05-02 194111](https://github.com/Proyectos1-FDI-UCM/c2324-Grupo09/assets/157683274/89316a59-b1e1-4498-8a6a-a31685f430a3)

**Comment by Javigozu** [comment]
## Fallo del Jump Kick cerca de una pared
### Descripción
Cuando el personaje se encuentra pegado a la pared y ejecuta el jump kick no rebota como debería.
### Pasos
1. Saltar hacia una pared (pulsando espacio)
2. Justo antes de llegar a ella ejecutar el jump kick (espacio otra vez). Comprobar que funciona normal y el personaje rebota en dirección contraria
3. Volver a saltar hacia una pared pero ejecutar el jump kick justo cuando se golpea la pared y no antes. Comprobar que el personaje no rebota, sino que hace un diminuto salto en el sitio y vuelve a pegarse a la pared.
### Captura de pantalla o vídeo

![Image](https://github.com/Proyectos1-FDI-UCM/c2324-Grupo09/assets/157632797/f52952f5-8856-4781-8856-ad0728a6781d)

**Comment by OscarMelquiadesDuranNarganes** [comment]
# SOBRE LOS BUGS
Parece ser que sí es posible crear issues para documentar bugs, sólo que desde la pantalla de Issues en vez de la board. Si no es un problema, os pediría que migréis todos estos bugs a sus issues individuales. Cierro este hilo para evitar más bugs donde no deberían estar.
